In [1]:
import numpy as np

import pandas as pd

from pandas import Series,DataFrame

In [2]:
df = DataFrame(np.random.randint(0,150,size = (100,5)),index = np.arange(100,200),columns=['Python','En','Math','Physic','Chem'])
df

     Python   En  Math  Physic  Chem
100     122   10     5      28    57
101      74  129    16     114    26
102      97  121   122      29    65
103     141   73   120     147     1
104     126  132    86     116    17
105      85    3    42     121    66
106     142   65     1     124    83
107     136  141   122      86   113
108      15   37   124     110   102
109      63   30    44      69    58
110      59   38   113     109    16
111       5   51    87      58   126
112      53   97    76      37    45
113      42  148   107      97   143
114      70  138    69      68   134
115      47  136   113      22    94
116      31  137     6      20    28
117     148   74   134       4   124
118     102   81   138     128    32
119      27  111    13      70    22
120      28   93   121      68     4
121     136   43    25      97    19
122     111   70    12      38    58
123      96  103   147      86     8
124      10   10    46      63   149
125       7   75    97     108    31
126      88    6   145     116    55
127      33   74   106      50    46
128      74   28    26     100    76
129      76   18   101     126   133
..      ...  ...   ...     ...   ...
170     144  124    77      92    82
171      36   98    48      43    80
172      51  143    68      34    74
173     149  117    18     141   120
174       8  139   146     112   122
175     115  101    64      62     9
176      10    7   140      45   148
177      65   43    68     109    18
178      31  100   110      49   123
179      29   46    69      57    90
180     146   86    18      22    46
181      71   50    40      90   140
182       4  100   147     116   110
183      55   87    93      78    34
184       5  109   124      87    82
185      10  118   139      50    51
186      32   12    71      36   124
187      94   16   138      13   149
188      65  101   123     128    86
189      43   94    10      29   132
190      68  135    94      28   125
191      30   60    98      27    15
192      89   16    10     135     4
193     104  139    97      29    17
194       5   29    41      99    91
195      19  102   135      41    40
196      58  100    70      82    64
197      84   97   129      76    13
198     131   15     7      44   114
199      79   37    95     128   116

[100 rows x 5 columns]

In [4]:
# 判断DataFrame是否存在空数据
df.isnull().any()

Python    False
En        False
Math      False
Physic    False
Chem      False
dtype: bool

In [6]:
df.notnull().all()

Python    True
En        True
Math      True
Physic    True
Chem      True
dtype: bool

In [12]:
100*5

500

In [13]:
for i in range(50):
    # 行索引
    index = np.random.randint(100,200,size =1)[0]

    cols = df.columns

    # 列索引
    col = np.random.choice(cols)

    df.loc[index,col] = None

In [15]:
for i in range(20):
    # 行索引
    index = np.random.randint(100,200,size =1)[0]

    cols = df.columns

    # 列索引
    col = np.random.choice(cols)

#     not a number 不是一个数
    df.loc[index,col] = np.NAN

In [16]:
df

     Python     En   Math  Physic   Chem
100   122.0   10.0    5.0    28.0   57.0
101     NaN  129.0   16.0   114.0   26.0
102    97.0  121.0  122.0    29.0   65.0
103   141.0   73.0  120.0   147.0    1.0
104   126.0    NaN   86.0   116.0   17.0
105    85.0    NaN   42.0   121.0   66.0
106   142.0   65.0    1.0   124.0   83.0
107   136.0  141.0    NaN    86.0  113.0
108    15.0   37.0  124.0   110.0  102.0
109    63.0   30.0    NaN    69.0   58.0
110     NaN    NaN  113.0   109.0   16.0
111     5.0   51.0   87.0    58.0  126.0
112    53.0   97.0   76.0    37.0   45.0
113    42.0  148.0    NaN    97.0    NaN
114    70.0  138.0   69.0    68.0  134.0
115     NaN  136.0  113.0    22.0   94.0
116    31.0  137.0    6.0    20.0   28.0
117   148.0   74.0  134.0     4.0  124.0
118   102.0   81.0  138.0   128.0   32.0
119    27.0  111.0   13.0     NaN   22.0
120    28.0   93.0  121.0     NaN    4.0
121   136.0    NaN   25.0    97.0   19.0
122   111.0   70.0   12.0    38.0   58.0
123     NaN  103.0  147.0    86.0    8.0
124    10.0   10.0   46.0    63.0  149.0
125     7.0   75.0   97.0   108.0   31.0
126    88.0    6.0    NaN     NaN   55.0
127    33.0   74.0  106.0    50.0   46.0
128    74.0   28.0   26.0   100.0   76.0
129    76.0   18.0  101.0     NaN    NaN
..      ...    ...    ...     ...    ...
170   144.0  124.0   77.0    92.0   82.0
171    36.0   98.0    NaN    43.0   80.0
172    51.0    NaN   68.0    34.0   74.0
173   149.0    NaN   18.0   141.0    NaN
174     8.0  139.0  146.0   112.0    NaN
175   115.0    NaN   64.0    62.0    9.0
176     NaN    7.0  140.0    45.0  148.0
177     NaN   43.0   68.0   109.0   18.0
178    31.0  100.0    NaN    49.0  123.0
179    29.0   46.0   69.0    57.0   90.0
180   146.0   86.0   18.0    22.0   46.0
181    71.0   50.0   40.0     NaN  140.0
182     4.0  100.0  147.0   116.0  110.0
183    55.0   87.0   93.0     NaN   34.0
184     NaN  109.0  124.0    87.0   82.0
185    10.0  118.0  139.0    50.0   51.0
186    32.0   12.0   71.0    36.0    NaN
187    94.0    NaN  138.0    13.0  149.0
188    65.0  101.0  123.0   128.0   86.0
189    43.0   94.0    NaN    29.0  132.0
190    68.0  135.0   94.0    28.0  125.0
191    30.0   60.0   98.0     NaN   15.0
192    89.0   16.0   10.0   135.0    4.0
193   104.0  139.0   97.0    29.0   17.0
194     5.0   29.0   41.0    99.0    NaN
195    19.0  102.0  135.0    41.0   40.0
196    58.0    NaN   70.0    82.0   64.0
197     NaN   97.0  129.0    76.0   13.0
198   131.0   15.0    NaN    44.0  114.0
199    79.0    NaN   95.0   128.0    NaN

[100 rows x 5 columns]

In [18]:
df.isnull().any()

Python    True
En        True
Math      True
Physic    True
Chem      True
dtype: bool

In [22]:
df.isnull().sum()

Python    14
En        14
Math      15
Physic    11
Chem      13
dtype: int64

In [23]:
df2 = df.copy()

In [24]:
df2.isnull().sum()

Python    14
En        14
Math      15
Physic    11
Chem      13
dtype: int64

In [26]:
# 固定值填充
df2.fillna(value=100)

     Python     En   Math  Physic   Chem
100   122.0   10.0    5.0    28.0   57.0
101   100.0  129.0   16.0   114.0   26.0
102    97.0  121.0  122.0    29.0   65.0
103   141.0   73.0  120.0   147.0    1.0
104   126.0  100.0   86.0   116.0   17.0
105    85.0  100.0   42.0   121.0   66.0
106   142.0   65.0    1.0   124.0   83.0
107   136.0  141.0  100.0    86.0  113.0
108    15.0   37.0  124.0   110.0  102.0
109    63.0   30.0  100.0    69.0   58.0
110   100.0  100.0  113.0   109.0   16.0
111     5.0   51.0   87.0    58.0  126.0
112    53.0   97.0   76.0    37.0   45.0
113    42.0  148.0  100.0    97.0  100.0
114    70.0  138.0   69.0    68.0  134.0
115   100.0  136.0  113.0    22.0   94.0
116    31.0  137.0    6.0    20.0   28.0
117   148.0   74.0  134.0     4.0  124.0
118   102.0   81.0  138.0   128.0   32.0
119    27.0  111.0   13.0   100.0   22.0
120    28.0   93.0  121.0   100.0    4.0
121   136.0  100.0   25.0    97.0   19.0
122   111.0   70.0   12.0    38.0   58.0
123   100.0  103.0  147.0    86.0    8.0
124    10.0   10.0   46.0    63.0  149.0
125     7.0   75.0   97.0   108.0   31.0
126    88.0    6.0  100.0   100.0   55.0
127    33.0   74.0  106.0    50.0   46.0
128    74.0   28.0   26.0   100.0   76.0
129    76.0   18.0  101.0   100.0  100.0
..      ...    ...    ...     ...    ...
170   144.0  124.0   77.0    92.0   82.0
171    36.0   98.0  100.0    43.0   80.0
172    51.0  100.0   68.0    34.0   74.0
173   149.0  100.0   18.0   141.0  100.0
174     8.0  139.0  146.0   112.0  100.0
175   115.0  100.0   64.0    62.0    9.0
176   100.0    7.0  140.0    45.0  148.0
177   100.0   43.0   68.0   109.0   18.0
178    31.0  100.0  100.0    49.0  123.0
179    29.0   46.0   69.0    57.0   90.0
180   146.0   86.0   18.0    22.0   46.0
181    71.0   50.0   40.0   100.0  140.0
182     4.0  100.0  147.0   116.0  110.0
183    55.0   87.0   93.0   100.0   34.0
184   100.0  109.0  124.0    87.0   82.0
185    10.0  118.0  139.0    50.0   51.0
186    32.0   12.0   71.0    36.0  100.0
187    94.0  100.0  138.0    13.0  149.0
188    65.0  101.0  123.0   128.0   86.0
189    43.0   94.0  100.0    29.0  132.0
190    68.0  135.0   94.0    28.0  125.0
191    30.0   60.0   98.0   100.0   15.0
192    89.0   16.0   10.0   135.0    4.0
193   104.0  139.0   97.0    29.0   17.0
194     5.0   29.0   41.0    99.0  100.0
195    19.0  102.0  135.0    41.0   40.0
196    58.0  100.0   70.0    82.0   64.0
197   100.0   97.0  129.0    76.0   13.0
198   131.0   15.0  100.0    44.0  114.0
199    79.0  100.0   95.0   128.0  100.0

[100 rows x 5 columns]

In [27]:
df2.mean()

Python    71.662791
En        75.627907
Math      77.929412
Physic    73.471910
Chem      69.080460
dtype: float64

In [29]:
# 均值
df3 = df2.fillna(value=df2.mean())
df3.astype(np.int16)

     Python   En  Math  Physic  Chem
100     122   10     5      28    57
101      71  129    16     114    26
102      97  121   122      29    65
103     141   73   120     147     1
104     126   75    86     116    17
105      85   75    42     121    66
106     142   65     1     124    83
107     136  141    77      86   113
108      15   37   124     110   102
109      63   30    77      69    58
110      71   75   113     109    16
111       5   51    87      58   126
112      53   97    76      37    45
113      42  148    77      97    69
114      70  138    69      68   134
115      71  136   113      22    94
116      31  137     6      20    28
117     148   74   134       4   124
118     102   81   138     128    32
119      27  111    13      73    22
120      28   93   121      73     4
121     136   75    25      97    19
122     111   70    12      38    58
123      71  103   147      86     8
124      10   10    46      63   149
125       7   75    97     108    31
126      88    6    77      73    55
127      33   74   106      50    46
128      74   28    26     100    76
129      76   18   101      73    69
..      ...  ...   ...     ...   ...
170     144  124    77      92    82
171      36   98    77      43    80
172      51   75    68      34    74
173     149   75    18     141    69
174       8  139   146     112    69
175     115   75    64      62     9
176      71    7   140      45   148
177      71   43    68     109    18
178      31  100    77      49   123
179      29   46    69      57    90
180     146   86    18      22    46
181      71   50    40      73   140
182       4  100   147     116   110
183      55   87    93      73    34
184      71  109   124      87    82
185      10  118   139      50    51
186      32   12    71      36    69
187      94   75   138      13   149
188      65  101   123     128    86
189      43   94    77      29   132
190      68  135    94      28   125
191      30   60    98      73    15
192      89   16    10     135     4
193     104  139    97      29    17
194       5   29    41      99    69
195      19  102   135      41    40
196      58   75    70      82    64
197      71   97   129      76    13
198     131   15    77      44   114
199      79   75    95     128    69

[100 rows x 5 columns]

In [31]:
nd = np.random.randint(0,20,size = 10)
nd

array([ 6, 18,  1, 17, 19,  5, 17, 16, 13,  3])

In [33]:
nd.sort()
nd

array([ 1,  3,  5,  6, 13, 16, 17, 17, 18, 19])

In [34]:
(13 + 16)/2

14.5

In [35]:
np.median(nd)

14.5

In [36]:
# 中位数填充
df2.median()
df4 = df2.fillna(df2.median())
df4

     Python     En   Math  Physic   Chem
100   122.0   10.0    5.0    28.0   57.0
101    68.0  129.0   16.0   114.0   26.0
102    97.0  121.0  122.0    29.0   65.0
103   141.0   73.0  120.0   147.0    1.0
104   126.0   82.5   86.0   116.0   17.0
105    85.0   82.5   42.0   121.0   66.0
106   142.0   65.0    1.0   124.0   83.0
107   136.0  141.0   86.0    86.0  113.0
108    15.0   37.0  124.0   110.0  102.0
109    63.0   30.0   86.0    69.0   58.0
110    68.0   82.5  113.0   109.0   16.0
111     5.0   51.0   87.0    58.0  126.0
112    53.0   97.0   76.0    37.0   45.0
113    42.0  148.0   86.0    97.0   65.0
114    70.0  138.0   69.0    68.0  134.0
115    68.0  136.0  113.0    22.0   94.0
116    31.0  137.0    6.0    20.0   28.0
117   148.0   74.0  134.0     4.0  124.0
118   102.0   81.0  138.0   128.0   32.0
119    27.0  111.0   13.0    69.0   22.0
120    28.0   93.0  121.0    69.0    4.0
121   136.0   82.5   25.0    97.0   19.0
122   111.0   70.0   12.0    38.0   58.0
123    68.0  103.0  147.0    86.0    8.0
124    10.0   10.0   46.0    63.0  149.0
125     7.0   75.0   97.0   108.0   31.0
126    88.0    6.0   86.0    69.0   55.0
127    33.0   74.0  106.0    50.0   46.0
128    74.0   28.0   26.0   100.0   76.0
129    76.0   18.0  101.0    69.0   65.0
..      ...    ...    ...     ...    ...
170   144.0  124.0   77.0    92.0   82.0
171    36.0   98.0   86.0    43.0   80.0
172    51.0   82.5   68.0    34.0   74.0
173   149.0   82.5   18.0   141.0   65.0
174     8.0  139.0  146.0   112.0   65.0
175   115.0   82.5   64.0    62.0    9.0
176    68.0    7.0  140.0    45.0  148.0
177    68.0   43.0   68.0   109.0   18.0
178    31.0  100.0   86.0    49.0  123.0
179    29.0   46.0   69.0    57.0   90.0
180   146.0   86.0   18.0    22.0   46.0
181    71.0   50.0   40.0    69.0  140.0
182     4.0  100.0  147.0   116.0  110.0
183    55.0   87.0   93.0    69.0   34.0
184    68.0  109.0  124.0    87.0   82.0
185    10.0  118.0  139.0    50.0   51.0
186    32.0   12.0   71.0    36.0   65.0
187    94.0   82.5  138.0    13.0  149.0
188    65.0  101.0  123.0   128.0   86.0
189    43.0   94.0   86.0    29.0  132.0
190    68.0  135.0   94.0    28.0  125.0
191    30.0   60.0   98.0    69.0   15.0
192    89.0   16.0   10.0   135.0    4.0
193   104.0  139.0   97.0    29.0   17.0
194     5.0   29.0   41.0    99.0   65.0
195    19.0  102.0  135.0    41.0   40.0
196    58.0   82.5   70.0    82.0   64.0
197    68.0   97.0  129.0    76.0   13.0
198   131.0   15.0   86.0    44.0  114.0
199    79.0   82.5   95.0   128.0   65.0

[100 rows x 5 columns]

In [37]:
# 众数填充，数量最多的那个数
df2

     Python     En   Math  Physic   Chem
100   122.0   10.0    5.0    28.0   57.0
101     NaN  129.0   16.0   114.0   26.0
102    97.0  121.0  122.0    29.0   65.0
103   141.0   73.0  120.0   147.0    1.0
104   126.0    NaN   86.0   116.0   17.0
105    85.0    NaN   42.0   121.0   66.0
106   142.0   65.0    1.0   124.0   83.0
107   136.0  141.0    NaN    86.0  113.0
108    15.0   37.0  124.0   110.0  102.0
109    63.0   30.0    NaN    69.0   58.0
110     NaN    NaN  113.0   109.0   16.0
111     5.0   51.0   87.0    58.0  126.0
112    53.0   97.0   76.0    37.0   45.0
113    42.0  148.0    NaN    97.0    NaN
114    70.0  138.0   69.0    68.0  134.0
115     NaN  136.0  113.0    22.0   94.0
116    31.0  137.0    6.0    20.0   28.0
117   148.0   74.0  134.0     4.0  124.0
118   102.0   81.0  138.0   128.0   32.0
119    27.0  111.0   13.0     NaN   22.0
120    28.0   93.0  121.0     NaN    4.0
121   136.0    NaN   25.0    97.0   19.0
122   111.0   70.0   12.0    38.0   58.0
123     NaN  103.0  147.0    86.0    8.0
124    10.0   10.0   46.0    63.0  149.0
125     7.0   75.0   97.0   108.0   31.0
126    88.0    6.0    NaN     NaN   55.0
127    33.0   74.0  106.0    50.0   46.0
128    74.0   28.0   26.0   100.0   76.0
129    76.0   18.0  101.0     NaN    NaN
..      ...    ...    ...     ...    ...
170   144.0  124.0   77.0    92.0   82.0
171    36.0   98.0    NaN    43.0   80.0
172    51.0    NaN   68.0    34.0   74.0
173   149.0    NaN   18.0   141.0    NaN
174     8.0  139.0  146.0   112.0    NaN
175   115.0    NaN   64.0    62.0    9.0
176     NaN    7.0  140.0    45.0  148.0
177     NaN   43.0   68.0   109.0   18.0
178    31.0  100.0    NaN    49.0  123.0
179    29.0   46.0   69.0    57.0   90.0
180   146.0   86.0   18.0    22.0   46.0
181    71.0   50.0   40.0     NaN  140.0
182     4.0  100.0  147.0   116.0  110.0
183    55.0   87.0   93.0     NaN   34.0
184     NaN  109.0  124.0    87.0   82.0
185    10.0  118.0  139.0    50.0   51.0
186    32.0   12.0   71.0    36.0    NaN
187    94.0    NaN  138.0    13.0  149.0
188    65.0  101.0  123.0   128.0   86.0
189    43.0   94.0    NaN    29.0  132.0
190    68.0  135.0   94.0    28.0  125.0
191    30.0   60.0   98.0     NaN   15.0
192    89.0   16.0   10.0   135.0    4.0
193   104.0  139.0   97.0    29.0   17.0
194     5.0   29.0   41.0    99.0    NaN
195    19.0  102.0  135.0    41.0   40.0
196    58.0    NaN   70.0    82.0   64.0
197     NaN   97.0  129.0    76.0   13.0
198   131.0   15.0    NaN    44.0  114.0
199    79.0    NaN   95.0   128.0    NaN

[100 rows x 5 columns]

In [42]:
df = DataFrame(np.random.randint(0,150,size = (2000,5)),index = np.arange(100,2100),columns=['Python','En','Math','Physic','Chem'])
df

      Python   En  Math  Physic  Chem
100       82   89    99     101   125
101        4   31   109      32     5
102       56  103    56      61    90
103       47  100   147     138    99
104       38   46    82      75    44
105       18   11   122       3   126
106       56   26   106      14   139
107        3  137    75      67   144
108       35   47   102      60    63
109       86  126    57      88   149
110       19  140    30      35    33
111       76    1     5      11    33
112       31   54    91     119    69
113       64   37    50      23    21
114       72   57   138      15    21
115       55  120   104      32    25
116       96   24    89      22   146
117       63    0     8      64    89
118       28   46   125      82    74
119       85   39    70     132   111
120      109   90    44      74    39
121        2  148   103     114    65
122      110   29    99      80    57
123      109   88    81     135    71
124       70  103   134     121   121
125       51   92   117      27    43
126        6   92    97      59   105
127       65   90    52     148    22
128        4  129    17     119    13
129       24  100   107      28   139
...      ...  ...   ...     ...   ...
2070     127   77    24      16    31
2071      93   61     9      28    22
2072     116   61    54       8    61
2073       4   72   140     112    34
2074      26  108   123      32    33
2075      46  130   135     124   113
2076      33   18   136      38    20
2077     107   11   129      54   119
2078      84   55   129      37    87
2079      95   50    45      19    84
2080     124   74    65     140    53
2081      26   35   149     145   127
2082      19   21   101       3    89
2083      84   10   131      71     4
2084      28   74   105      68    89
2085      23   93    84      97    88
2086      86  133    26     125    13
2087      21  124    40     115     5
2088      20   15    35      31    37
2089      96  123   123       5    64
2090      22   43    92      78    60
2091      16   31    17      60    58
2092      65   18    13      13    34
2093      69   49   109      40    58
2094     128   46    10      82   111
2095      26   59     8      54   149
2096     111   47    90      92    66
2097       5   97    73     140   104
2098     102    6     7       5   119
2099      97   19    77     143    48

[2000 rows x 5 columns]

In [43]:
for i in range(1000):
    # 行索引
    index = np.random.randint(100,2100,size =1)[0]

    cols = df.columns

    # 列索引
    col = np.random.choice(cols)

    df.loc[index,col] = None

In [44]:
df.isnull().sum()

Python    190
En        200
Math      194
Physic    189
Chem      181
dtype: int64

In [45]:
df.head()

     Python     En   Math  Physic   Chem
100    82.0   89.0   99.0   101.0  125.0
101     4.0   31.0  109.0    32.0    5.0
102    56.0  103.0   56.0     NaN   90.0
103    47.0  100.0  147.0   138.0   99.0
104    38.0   46.0    NaN    75.0   44.0

In [46]:
df.tail()

      Python    En  Math  Physic   Chem
2095    26.0  59.0   8.0    54.0  149.0
2096     NaN  47.0  90.0    92.0   66.0
2097     5.0  97.0  73.0   140.0  104.0
2098   102.0   6.0   7.0     5.0  119.0
2099    97.0  19.0  77.0     NaN   48.0

In [48]:
# 去重之后的数据
df['Python'].unique()

array([ 82.,   4.,  56.,  47.,  38.,  18.,   3.,  35.,  86.,  19.,  76.,
        31.,  64.,  72.,  55.,  96.,  63.,  28.,  85., 109.,   2., 110.,
        70.,  51.,   6.,  65.,  24.,  48.,  44.,  11., 114., 129.,  87.,
       108., 125.,  nan, 140., 132.,  91.,  34.,  54.,  30.,  12.,  98.,
       142.,  79.,  13.,  77.,  40., 139.,  39.,  81., 112.,  36.,  22.,
         5., 120.,  17., 127., 119.,  59., 146.,  89., 103.,   8.,  97.,
       130.,  73.,  83., 122.,  95., 100.,  41.,  21., 136.,  80., 101.,
        50.,  27.,  71.,  16., 141., 126., 102., 145.,  15.,  52.,  94.,
        10.,  33., 137.,   9., 128.,  88.,  26.,  84.,  93.,   1.,   7.,
       131., 107., 148.,   0., 105.,  66.,  32., 115., 118.,  58.,  53.,
        29.,  42.,  57.,  62.,  25.,  60.,  69., 133.,  68.,  20., 106.,
       147.,  78.,  90., 124., 149.,  92.,  75., 117., 143.,  99.,  37.,
       123.,  45.,  61., 121., 135., 138., 116.,  14., 104.,  74.,  46.,
       111.,  23.,  43.,  49., 144., 113.,  67., 134.])

In [49]:
df['Python'].value_counts()

143.0    20
136.0    20
102.0    19
105.0    19
26.0     19
69.0     19
31.0     18
148.0    18
75.0     18
139.0    18
1.0      18
35.0     17
140.0    17
110.0    17
125.0    17
146.0    17
141.0    17
64.0     16
30.0     16
79.0     16
73.0     16
40.0     16
10.0     15
6.0      15
65.0     15
81.0     15
28.0     15
48.0     15
92.0     15
103.0    15
         ..
104.0     9
12.0      9
116.0     9
13.0      9
59.0      9
93.0      9
124.0     9
85.0      8
135.0     8
131.0     8
68.0      8
66.0      8
62.0      8
120.0     8
17.0      8
25.0      8
145.0     7
58.0      7
134.0     7
113.0     7
123.0     7
39.0      7
34.0      7
43.0      7
74.0      6
144.0     6
132.0     6
142.0     5
67.0      5
49.0      5
Name: Python, Length: 150, dtype: int64

In [53]:
en = df['En'].value_counts()
en

8.0      21
96.0     19
118.0    19
24.0     19
43.0     19
27.0     19
19.0     19
41.0     18
0.0      18
3.0      18
52.0     18
4.0      17
137.0    17
1.0      17
101.0    17
51.0     17
39.0     17
100.0    17
127.0    17
115.0    16
33.0     16
112.0    16
92.0     16
126.0    16
133.0    15
32.0     15
89.0     15
95.0     15
36.0     15
93.0     15
         ..
12.0      9
28.0      9
106.0     9
45.0      9
80.0      9
84.0      9
58.0      9
79.0      9
71.0      9
83.0      9
142.0     9
7.0       9
6.0       8
61.0      8
149.0     8
34.0      8
20.0      8
38.0      8
130.0     8
104.0     7
120.0     7
56.0      7
146.0     7
98.0      7
134.0     6
123.0     6
35.0      6
87.0      5
42.0      5
119.0     4
Name: En, Length: 150, dtype: int64

In [54]:
en.index[0]

8.0

In [52]:
s = df.median()
print(s,type(s))

Python    75.0
En        74.0
Math      77.5
Physic    73.0
Chem      72.0
dtype: float64 <class 'pandas.core.series.Series'>

In [55]:
zhongshu = []
for col in df.columns:
    zhongshu.append(df[col].value_counts().index[0])

In [57]:
s = Series(zhongshu,index = df.columns)
s

Python    143.0
En          8.0
Math       80.0
Physic     31.0
Chem      125.0
dtype: float64

In [60]:
df2 = df.fillna(s)
df2

      Python     En   Math  Physic   Chem
100     82.0   89.0   99.0   101.0  125.0
101      4.0   31.0  109.0    32.0    5.0
102     56.0  103.0   56.0    31.0   90.0
103     47.0  100.0  147.0   138.0   99.0
104     38.0   46.0   80.0    75.0   44.0
105     18.0   11.0  122.0     3.0  126.0
106     56.0   26.0  106.0    14.0  139.0
107      3.0  137.0   75.0    67.0  144.0
108     35.0   47.0  102.0    60.0   63.0
109     86.0  126.0   80.0    88.0  149.0
110     19.0  140.0   80.0    35.0   33.0
111     76.0    8.0    5.0    11.0   33.0
112     31.0   54.0   91.0   119.0   69.0
113     64.0   37.0   50.0    23.0   21.0
114     72.0   57.0  138.0    15.0   21.0
115     55.0  120.0  104.0    32.0   25.0
116     96.0   24.0   89.0    31.0  146.0
117     63.0    8.0    8.0    64.0   89.0
118     28.0    8.0  125.0    82.0   74.0
119     85.0   39.0   70.0   132.0  111.0
120    109.0   90.0   80.0    74.0   39.0
121      2.0    8.0  103.0   114.0   65.0
122    110.0   29.0   99.0    80.0   57.0
123    109.0   88.0   81.0   135.0   71.0
124     70.0  103.0  134.0   121.0  121.0
125     51.0   92.0  117.0    31.0   43.0
126      6.0   92.0   97.0    59.0  105.0
127     65.0   90.0   52.0   148.0   22.0
128      4.0  129.0   17.0   119.0   13.0
129     24.0  100.0  107.0    28.0  139.0
...      ...    ...    ...     ...    ...
2070   127.0   77.0   24.0    16.0  125.0
2071    93.0   61.0    9.0    28.0   22.0
2072   116.0   61.0   54.0     8.0   61.0
2073     4.0   72.0  140.0    31.0   34.0
2074   143.0  108.0  123.0    32.0   33.0
2075    46.0    8.0  135.0   124.0  113.0
2076   143.0   18.0  136.0    38.0  125.0
2077   143.0   11.0  129.0    54.0  119.0
2078    84.0   55.0  129.0    37.0   87.0
2079    95.0   50.0   45.0    19.0   84.0
2080   124.0   74.0   65.0    31.0   53.0
2081    26.0   35.0  149.0   145.0  127.0
2082    19.0   21.0  101.0     3.0   89.0
2083    84.0    8.0  131.0    71.0    4.0
2084    28.0   74.0  105.0    68.0   89.0
2085    23.0   93.0   84.0    97.0   88.0
2086    86.0  133.0   26.0   125.0   13.0
2087    21.0  124.0   40.0    31.0    5.0
2088    20.0   15.0   35.0    31.0   37.0
2089    96.0  123.0  123.0     5.0   64.0
2090    22.0   43.0   92.0    78.0   60.0
2091    16.0   31.0   17.0    60.0   58.0
2092    65.0   18.0   13.0    13.0   34.0
2093    69.0   49.0  109.0    40.0   58.0
2094   128.0   46.0   10.0    82.0  111.0
2095    26.0   59.0    8.0    54.0  149.0
2096   143.0   47.0   90.0    92.0   66.0
2097     5.0   97.0   73.0   140.0  104.0
2098   102.0    6.0    7.0     5.0  119.0
2099    97.0   19.0   77.0    31.0   48.0

[2000 rows x 5 columns]

In [61]:
df2.isnull().sum()

Python    0
En        0
Math      0
Physic    0
Chem      0
dtype: int64

In [62]:
df.isnull().sum()

Python    190
En        200
Math      194
Physic    189
Chem      181
dtype: int64

In [65]:
df3 = df.iloc[:20]
df3

     Python     En   Math  Physic   Chem
100    82.0   89.0   99.0   101.0  125.0
101     4.0   31.0  109.0    32.0    5.0
102    56.0  103.0   56.0     NaN   90.0
103    47.0  100.0  147.0   138.0   99.0
104    38.0   46.0    NaN    75.0   44.0
105    18.0   11.0  122.0     3.0  126.0
106    56.0   26.0  106.0    14.0  139.0
107     3.0  137.0   75.0    67.0  144.0
108    35.0   47.0  102.0    60.0   63.0
109    86.0  126.0    NaN    88.0  149.0
110    19.0  140.0    NaN    35.0   33.0
111    76.0    NaN    5.0    11.0   33.0
112    31.0   54.0   91.0   119.0   69.0
113    64.0   37.0   50.0    23.0   21.0
114    72.0   57.0  138.0    15.0   21.0
115    55.0  120.0  104.0    32.0   25.0
116    96.0   24.0   89.0     NaN  146.0
117    63.0    NaN    8.0    64.0   89.0
118    28.0    NaN  125.0    82.0   74.0
119    85.0   39.0   70.0   132.0  111.0

In [70]:
'''method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
    Method to use for filling holes in reindexed Series
    pad / ffill: propagate last valid observation forward to next valid
    backfill / bfill: use NEXT valid observation to fill gap'''
df3.fillna(method='bfill',axis = 1)

     Python     En   Math  Physic   Chem
100    82.0   89.0   99.0   101.0  125.0
101     4.0   31.0  109.0    32.0    5.0
102    56.0  103.0   56.0    90.0   90.0
103    47.0  100.0  147.0   138.0   99.0
104    38.0   46.0   75.0    75.0   44.0
105    18.0   11.0  122.0     3.0  126.0
106    56.0   26.0  106.0    14.0  139.0
107     3.0  137.0   75.0    67.0  144.0
108    35.0   47.0  102.0    60.0   63.0
109    86.0  126.0   88.0    88.0  149.0
110    19.0  140.0   35.0    35.0   33.0
111    76.0    5.0    5.0    11.0   33.0
112    31.0   54.0   91.0   119.0   69.0
113    64.0   37.0   50.0    23.0   21.0
114    72.0   57.0  138.0    15.0   21.0
115    55.0  120.0  104.0    32.0   25.0
116    96.0   24.0   89.0   146.0  146.0
117    63.0    8.0    8.0    64.0   89.0
118    28.0  125.0  125.0    82.0   74.0
119    85.0   39.0   70.0   132.0  111.0

In [71]:
#数据量足够大，空数据比较少，直接删除
df.shape

(2000, 5)

In [ ]:
df.dro